#!/bin/bash

set -ev

git pull https://github.com/droundy/sad-monte-carlo.git
git pull https://github.com/cadetrotter/sad-monte-carlo.git
git pull https://github.com/vandegja/sad-monte-carlo.git
git pull https://github.com/kiatvonj/sad-monte-carlo.git
git pull https://github.com/Jordan-Pommerenck/sad-monte-carlo.git
