#!/bin/bash

set -ev

git pull https://github.com/droundy/sad-monte-carlo.git
git pull https://github.com/ThunderChief33/sad-monte-carlo.git
git pull https://github.com/smay26/sad-monte-carlo.git
git pull https://github.com/HenrySprueill/sad-monte-carlo.git
git pull https://github.com/Holmesle/sad-monte-carlo.git
git pull https://github.com/Frank-the-dog/sad-monte-carlo.git