#!/bin/bash

set -ev

git pull https://github.com/droundy/sad-monte-carlo.git
git pull https://github.com/kzvi/sad-monte-carlo.git
git pull https://github.com/ThunderChief33/sad-monte-carlo.git
git pull https://github.com/legendMK13/sad-monte-carlo.git
